### ISSUE TITLE
Segment not pinging Knowtify

### ISSUE THREAD

**Issue by DaneLyons** [segmentio/integration-knowtify#2]
Our webhook isn't getting a request from Segment when a new identify or track event happens.

All tests pass when running mocha ./test/index.js

**Comment by f2prateek** [comment]
@DaneLyons we haven't deployed it yet, I'll confirm with @amillet89 and let you know once we do.

**Comment by DaneLyons** [comment]
@f2prateek thanks for the update!

**Comment by f2prateek** [comment]
I did deploy this yesterday, let me know if it's not working yet.
